# frozen_string_literal: true

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 20 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  primary: &primary_development
    <<: *default
    database: charkeeper_development
  errors:
    <<: *primary_development
    database: charkeeper_development_errors
    migrations_paths: db/errors_migrate

local_production:
  <<: *default
  database: charkeeper_development

test:
  primary: &primary_test
    <<: *default
    database: charkeeper_test
  errors:
    <<: *primary_test
    database: charkeeper_test_errors
    migrations_paths: db/errors_migrate

production:
  primary: &primary_production
    <<: *default
    database: charkeeper
    username: charkeeper
    password: <%= Rails.application.credentials[:database_password] %>
  errors:
    <<: *primary_production
    database: charkeeper_errors
    migrations_paths: db/errors_migrate
