local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

minio:
  service: S3
  endpoint: <%= Rails.application.credentials.dig(Rails.env.to_sym, :minio, :endpoint) %>
  force_path_style: true
  access_key_id: <%= Rails.application.credentials.dig(Rails.env.to_sym, :minio, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(Rails.env.to_sym, :minio, :secret_access_key) %>
  bucket: <%= Rails.application.credentials.dig(Rails.env.to_sym, :minio, :bucket) %>
  region: <%= Rails.application.credentials.dig(Rails.env.to_sym, :minio, :region) %>
