local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

minio:
  service: S3
  endpoint: https://s3.charkeeper.org
  access_key_id: 
  secret_access_key: 
  bucket: charkeeper-<%= Rails.env %>
  region: region
